; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:uhat_g431cbu6]
platform = ststm32
board = uhat_g431cbu6
framework = mbed
board_build.mbed_variant = NUCLEO_G431RB
upload_protocol = stlink
board_upload.maximum_ram_size = 32768
board_upload.maximum_size = 131072
lib_compat_mode = off
monitor_speed = 9600

;[env:genericSTM32F103CB]
;platform = ststm32
;board = genericSTM32F103CB
;framework = Arduino
;upload_protocol = serial
;upload_port = ttyUSB0
